### ISSUE TITLE
Unresponsive :(

### ISSUE THREAD

**Issue by rhettl** [mnort9/goosecon#1]
Hello, love the idea, makes me less likely to write scratch files just to test out my model methods.
That said, my goosecon is unresponsive. 

node@4.2.2
npm@3.4.0

Here is the console output:

```
$ goosecon --mongo-db 'mongodb://localhost/my-db'

/** Got rid of large GOOSECON header from quoted text, it was garbled here **/

Loading Modules...
> 
2 Modules Loaded:
Day, Student

> Student.findOne().populate('day')
> 
> 
> 
> 
> Student.findOne().populate('day')

> 
> 
```

On loading, it reveals that it found `Day` and `Student`. I then give the eval `Student.findOne()`, or `.find()` or pretty much anything standard, and if responds with an empty line. It doesn't do anything until I hit enter. 

Thank you for any help available!

**Comment by mnort9** [comment]
Try specifying your project's mongoose directory as a command line argument or in `.gooseconrc`

`--mongoose-dir './node_modules/mongoose'`

**Comment by rhettl** [comment]
Fixed, Awesome! :+1:

**Comment by rhettl** [comment]
Reading the whole readme helps  =>> https://github.com/mnort9/goosecon#note-fix-query-stalling-error
